name: "MP2"
semester: "Fall2018"
version: 1.0.0
grading:
  timeout: PT5M
  run: "./gradlew grade -Pgrade.capture -Pgrade.secure -Pgrade.reporting.file={{ gradeFile }}"
  ignoreOutput:
    - "^java.security.policy: error parsing file.*"
    - "^Unable to initialize policy entry:.*"
    - "^.*?expected \\[\\;\\], found \\[priority\\]$"
    - "^WARNING: An illegal reflective access operation has occurred.*"
    - "^WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass.*"
    - "^WARNING: Please consider reporting this to the maintainers.*"
    - "^WARNING: Use --illegal-access=warn to enable warnings.*"
    - "^WARNING: All illegal access operations will be denied in a future release.*"
    - "^The TaskInternal.*"
scoring:
  max: 100
  selectors:
    - checkstyle
    - test
forceCommitAfterPoints: true
vcs:
  git: true
students:
  location: email.txt
  require: true
  count: 1
  suffix: "@illinois.edu"
files:
  - "Anagram"
  - "CheckPassword"
  - "StringSplitter"
  - "TimesTable"
secure: config/security.policy
reporting:
  post: "https://cs125-reporting.cs.illinois.edu/progress"
checkstyle:
  name: "checkstyle Tests"
  missing:
    score: 0
    message: "checkstyle failed to run"
    name: "checkstyle"
  selectors:
    - selector: "count(//file/error) = 0"
      score: 10
      message: "No checkstyle errors were reported"
      name: "checkstyle"
    - selector: "count(//file/error) > 0"
      score: 0
      message: "checkstyle errors were reported"
      name: "checkstyle"
notes:
  "Note that the maximum local grade is 90/100. 10 points will be provided
  during official grading if you have submitted code that earns at least 20
  points by Friday 9/21/2018 at 5PM."
test:
  name: "testNG Tests"
  selectors:
    - selector: "count(//testcase[@name='gradeAreStrictAnagrams']) = 1 and count(//testcase[@name='gradeAreStrictAnagrams']//failure) = 0"
      score: 20
      message: "No test failures in Anagram"
      name: "Anagram"
    - selector: "count(//testcase[@name='gradeAreStrictAnagrams']) = 1 and count(//testcase[@name='gradeAreStrictAnagrams']//failure) > 0"
      score: 0
      message: "Test failures in Anagram"
      name: "Anagram"
    - selector: "count(//testcase[@name='gradeAreStrictAnagrams']) = 0"
      score: 0
      message: "Anagram didn't compile"
      name: "Anagram"
    - selector: "count(//testcase[@name='gradeCheckAPassword']) = 1 and count(//testcase[@name='gradeCheckAPassword']//failure) = 0"
      score: 20
      message: "No test failures in CheckPassword"
      name: "CheckPassword"
    - selector: "count(//testcase[@name='gradeCheckAPassword']) = 1 and count(//testcase[@name='gradeCheckAPassword']//failure) > 0"
      score: 0
      message: "Test failures in CheckPassword"
      name: "CheckPassword"
    - selector: "count(//testcase[@name='gradeCheckAPassword']) = 0"
      score: 0
      message: "CheckPassword didn't compile"
      name: "CheckPassword"
    - selector: "count(//testcase[@name='gradeStringSplitter']) = 1 and count(//testcase[@name='gradeStringSplitter']//failure) = 0"
      score: 20
      message: "No test failures in StringSplitter"
      name: "StringSplitter"
    - selector: "count(//testcase[@name='gradeStringSplitter']) = 1 and count(//testcase[@name='gradeStringSplitter']//failure) > 0"
      score: 0
      message: "Test failures in StringSplitter"
      name: "StringSplitter"
    - selector: "count(//testcase[@name='gradeStringSplitter']) = 0"
      score: 0
      message: "StringSplitter didn't compile"
      name: "StringSplitter"
    - selector: "count(//testcase[@name='gradeGenerateTimesTable']) = 1 and count(//testcase[@name='gradeGenerateTimesTable']//failure) = 0"
      score: 20
      message: "No test failures in TimesTable"
      name: "TimesTable"
    - selector: "count(//testcase[@name='gradeGenerateTimesTable']) = 1 and count(//testcase[@name='gradeGenerateTimesTable']//failure) > 0"
      score: 0
      message: "Test failures in TimesTable"
      name: "TimesTable"
    - selector: "count(//testcase[@name='gradeGenerateTimesTable']) = 0"
      score: 0
      message: "TimesTable didn't compile"
      name: "TimesTable"

# vim: ts=2:sw=2:et
